In [2]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
df_credit = pd.read_csv('tmdb_5000_credits.csv')
df_movies = pd.read_csv('tmdb_5000_movies.csv')

In [4]:
df_credit.shape

(4803, 4)

In [5]:
df_movies.shape

(4803, 20)

In [6]:
df_credit.sample()

movie_id          title  \
3172      6521  The Contender   

                                                   cast  \
3172  [{"cast_id": 1, "character": "Sheldon Runyon",...   

                                                   crew  
3172  [{"credit_id": "59991a7fc3a3686d67007a52", "de...

In [7]:
# df_movies[df_movies['id'] == 9754] 
df_movies.sample()

budget                                             genres homepage   id  \
4457       0  [{"id": 18, "name": "Drama"}, {"id": 53, "name...      NaN  905   

                                               keywords original_language  \
4457  [{"id": 212, "name": "london england"}, {"id":...                de   

              original_title  \
4457  Die Büchse der Pandora   

                                               overview  popularity  \
4457  The rise and inevitable fall of an amoral but ...    1.824184   

                      production_companies  \
4457  [{"name": "Nero Films", "id": 4903}]   

                           production_countries release_date  revenue  \
4457  [{"iso_3166_1": "DE", "name": "Germany"}]   1929-01-30        0   

      runtime                          spoken_languages    status tagline  \
4457    109.0  [{"iso_639_1": "de", "name": "Deutsch"}]  Released     NaN   

              title  vote_average  vote_count  
4457  Pandora's Box           7.6          45

In [8]:
# df_movies.info()

In [9]:
df_movies = df_movies.merge(df_credit , on = 'title')

In [10]:
df_movies.sample(1)

budget                                             genres  \
3748  3600000  [{"id": 18, "name": "Drama"}, {"id": 10749, "n...   

                                               homepage   id  \
3748  http://www.mgm.com/title_title.do?title_star=L...  451   

                                               keywords original_language  \
3748  [{"id": 30, "name": "individual"}, {"id": 549,...                en   

         original_title                                           overview  \
3748  Leaving Las Vegas  Ben Sanderson, an alcoholic Hollywood screenwr...   

      popularity                               production_companies  ...  \
3748   22.030517  [{"name": "United Artists", "id": 60}, {"name"...  ...   

     runtime                          spoken_languages    status  \
3748   112.0  [{"iso_639_1": "en", "name": "English"}]  Released   

                             tagline              title vote_average  \
3748  I Love You... The Way You Are.  Leaving Las Vegas          7.1   

     vote_count movie_id                                               cast  \
3748        360      451  [{"cast_id": 1, "character": "Ben Sanderson", ...   

                                                   crew  
3748  [{"credit_id": "52fe4245c3a36847f80111c3", "de...  

[1 rows x 23 columns]

In [11]:
df_movies.shape

(4809, 23)

In [12]:
movies = df_movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [13]:
movies.sample()

movie_id              title  \
1047      9944  The Pelican Brief   

                                               overview  \
1047  Two Supreme Court Justices have been assassina...   

                                                 genres  \
1047  [{"id": 18, "name": "Drama"}, {"id": 9648, "na...   

                                               keywords  \
1047  [{"id": 934, "name": "judge"}, {"id": 1992, "n...   

                                                   cast  \
1047  [{"cast_id": 9, "character": "Darby Shaw", "cr...   

                                                   crew  
1047  [{"credit_id": "52fe454cc3a36847f80c6875", "de...

In [14]:
movies.dropna(inplace = True)

C:\Users\Sushant\AppData\Local\Temp\ipykernel_9696\3024812739.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.dropna(inplace = True)


In [15]:
movies.duplicated().sum()

0

In [16]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [17]:
import ast

In [18]:
def convert(text):
    list = []
    for i in ast.literal_eval(text):
        list.append(i['name'])
    return list

# CHANGING FORMAT FROM STRING TO LIST BY USING AST.LITERAL_EVAL(TEXT)

In [21]:
movies.genres = movies['genres'].apply(convert)


ValueError: malformed node or string: ['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [62]:
movies.keywords = movies['keywords'].apply(convert)

ValueError: malformed node or string: ['cultureclash', 'future', 'spacewar', 'spacecolony', 'society', 'spacetravel', 'futuristic', 'romance', 'space', 'alien', 'tribe', 'alienplanet', 'cgi', 'marine', 'soldier', 'battle', 'loveaffair', 'antiwar', 'powerrelations', 'mindandsoul', '3d']

In [ ]:
movies.sample()

In [ ]:
movies.cast = movies['cast'].apply(convert)
movies.cast = movies['cast'].apply(lambda x : x[0:3])

In [22]:
movies.sample()

movie_id title                                           overview  \
189     86834  Noah  A man who suffers visions of an apocalyptic de...   

                 genres                keywords  \
189  [Drama, Adventure]  [bible, god, noah, 3d]   

                                                  cast  \
189  [{"cast_id": 4, "character": "Noah", "credit_i...   

                                                  crew  
189  [{"credit_id": "53d8b3dec3a3682c43001c39", "de...

In [ ]:
movies['cast'][0]

In [24]:
def fetch_director(text):
    list = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            list.append(i['name'])
    
    return list



In [25]:
movies['crew'] = movies['crew'].apply(fetch_director)

C:\Users\Sushant\AppData\Local\Temp\ipykernel_9696\2884021428.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew'] = movies['crew'].apply(fetch_director)


In [26]:
movies.sample()

movie_id      title                                           overview  \
3105    222649  Rosewater  In 2009, Iranian Canadian journalist Maziar Ba...   

       genres                                           keywords  \
3105  [Drama]  [prison, biography, reporter, interrogation, i...   

                                                   cast           crew  
3105  [{"cast_id": 10, "character": "Maziar Bahari",...  [Jon Stewart]

In [27]:
def collapse(text):
    l1 = []
    for i in text:
        l1.append(i.replace(" " , ""))

    return l1

In [28]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

# the same function can be written as movies['cast'] = movies['cast'].apply[ lambda x : (i.replace(" ","") for i in x]

C:\Users\Sushant\AppData\Local\Temp\ipykernel_9696\3441128704.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast'] = movies['cast'].apply(collapse)
C:\Users\Sushant\AppData\Local\Temp\ipykernel_9696\3441128704.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew'] = movies['crew'].apply(collapse)
C:\Users\Sushant\AppData\Local\Temp\ipykernel_9696\3441128704.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,c

In [29]:
movies.sample(2)

movie_id                title  \
174       1724  The Incredible Hulk   
1890    319888      Eddie the Eagle   

                                               overview  \
174   Scientist Bruce Banner scours the planet for a...   
1890  Inspired by true events, Eddie the Eagle is a ...   

                                   genres  \
174   [ScienceFiction, Action, Adventure]   
1890             [Comedy, Drama, History]   

                                               keywords  \
174   [newyork, riodejaneiro, marvelcomic, superhero...   
1890  [underdog, olympicgames, skijump, biography, s...   

                                                   cast              crew  
174   [[, {, ", c, a, s, t, _, i, d, ", :, , 3, ,, ,...  [LouisLeterrier]  
1890  [[, {, ", c, a, s, t, _, i, d, ", :, , 5, ,, ,...  [DexterFletcher]

In [30]:
movies['overview'] = movies['overview'].apply(lambda x : x.split())

C:\Users\Sushant\AppData\Local\Temp\ipykernel_9696\2038387361.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['overview'] = movies['overview'].apply(lambda x : x.split())


In [31]:
movies.sample(2)

movie_id               title  \
2558      2493  The Princess Bride   
1402     34806    The Back-Up Plan   

                                               overview  \
2558  [In, this, enchantingly, cracked, fairy, tale,...   
1402  [When, Zoe, tires, of, looking, for, Mr., Righ...   

                                             genres  \
2558  [Adventure, Family, Fantasy, Comedy, Romance]   
1402                              [Comedy, Romance]   

                                               keywords  \
2558  [swashbuckler, evilprince, referencetosocrates...   
1402  [kiss, spermbank, romanticcomedy, malefemalere...   

                                                   cast         crew  
2558  [[, {, ", c, a, s, t, _, i, d, ", :, , 2, ,, ,...  [RobReiner]  
1402  [[, {, ", c, a, s, t, _, i, d, ", :, , 2, 2, ,...   [AlanPoul]

In [32]:
movies['tags'] = movies['overview'] +  movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

C:\Users\Sushant\AppData\Local\Temp\ipykernel_9696\2915464829.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'] = movies['overview'] +  movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']


In [33]:
new_df = movies.drop(columns = ['overview',	'genres',	'keywords',	'cast',	'crew'])

In [34]:
new_df.sample(3)

movie_id                   title  \
4186     44562  Ed and His Dead Mother   
3045    328425                The Gift   
2490      9689        Hollywood Ending   

                                                   tags  
4186  [A, mourning, son, makes, a, deal, to, reanima...  
3045  [A, husband, and, wife, try, to, reinvigorate,...  
2490  [Woody, Allen, stars, as, Val, Waxman,, a, two...

In [35]:
new_df['tags'] = new_df['tags'].apply(lambda x : " ".join(x))

In [36]:
new_df.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [37]:
cv = CountVectorizer(max_features = 5000, stop_words='english')

In [38]:
cv

CountVectorizer(max_features=5000, stop_words='english')

In [39]:
import nltk

In [40]:
from nltk.stem.porter import PorterStemmer


In [41]:
ps = PorterStemmer()

In [42]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

# we were facing the similar words having different feature column issue like 'actor' and 'actors' are similar words but they were treated different so we stem them up

In [43]:
new_df['tags'] = new_df['tags'].apply(stem)

In [44]:
new_df['tags']

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...                        
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [45]:
print(cv.fit_transform(new_df['tags']).toarray().shape)
vectors = cv.fit_transform(new_df['tags']).toarray()

(4806, 5000)


In [46]:
# as we can see we have 4806 rows (movies) and 5000 words in each row

In [47]:
# now we will calculate cosine distance to find out similarity of each movie with others 
# eventually we are directly using similarity function as it will be 1 stage solution

In [48]:
from sklearn.metrics.pairwise import cosine_similarity

In [49]:
similarity = cosine_similarity(vectors)

In [50]:
similarity.shape

(4806, 4806)

In [51]:
# we can see we got 4806*4806 table because we are calculating distance of each vetor with other vectors present in the dataset

In [52]:
# now we need to fetch top 5 similar vectors and recommend their name as list

In [53]:
sorted(similarity[0] , reverse = True)

[0.9999999999999998,
 0.28102505044048826,
 0.2657423679108717,
 0.26401000024165,
 0.26130213378560535,
 0.2484013136974297,
 0.24784079854830487,
 0.24239308278185984,
 0.23995690956687135,
 0.23995690956687135,
 0.23728949893812473,
 0.22779791898059973,
 0.2256354947537551,
 0.22147019900891643,
 0.21919864974047634,
 0.2152488010002526,
 0.21524880100025257,
 0.2113701265354594,
 0.2101050788156825,
 0.2101050788156825,
 0.21010507881568247,
 0.2092457497388747,
 0.20549873413169661,
 0.20345964269592334,
 0.20134681656420733,
 0.20134681656420733,
 0.19936305570722498,
 0.19936305570722498,
 0.19827263883864388,
 0.19727878476642874,
 0.19649437297296482,
 0.195976600339204,
 0.19184045508446734,
 0.18983159915049982,
 0.1898315991504998,
 0.18857857160117855,
 0.18857857160117855,
 0.18668326147193276,
 0.18668326147193276,
 0.18641092980036,
 0.18641092980036,
 0.18380365552345193,
 0.1823843010350213,
 0.1821250481661794,
 0.1821250481661794,
 0.18195633571851272,
 0.177571201

In [54]:
# we can get the sorted vectors but we lost which vector are these top vectors as we lost their index(column index)

In [55]:
# so we will enumerate and make it index similarity (key-value) pair and then convert it to list

In [56]:
list(enumerate(similarity))

[(0,
  array([1.        , 0.08858079, 0.09004503, ..., 0.04559608, 0.        ,
         0.        ])),
 (1,
  array([0.08858079, 1.        , 0.06558258, ..., 0.02490677, 0.        ,
         0.0277137 ])),
 (2,
  array([0.09004503, 0.06558258, 1.        , ..., 0.02531848, 0.        ,
         0.        ])),
 (3,
  array([0.07352146, 0.04016097, 0.06123724, ..., 0.03100868, 0.04841229,
         0.08625819])),
 (4,
  array([0.19184046, 0.07859438, 0.07989355, ..., 0.02022783, 0.08421519,
         0.04501491])),
 (5,
  array([0.11290969, 0.12335343, 0.07523548, ..., 0.01904848, 0.05947887,
         0.04239039])),
 (6,
  array([0.03958262, 0.02162194, 0.02197935, ..., 0.        , 0.0347524 ,
         0.        ])),
 (7,
  array([0.15404885, 0.14024818, 0.14256649, ..., 0.        , 0.04508348,
         0.04819627])),
 (8,
  array([0.06105625, 0.06670373, 0.06780635, ..., 0.05150262, 0.10721125,
         0.11461365])),
 (9,
  array([0.09913632, 0.10830607, 0.11009638, ..., 0.02090605, 0.0217

In [57]:
# we will get an array of array and we need to sort then in descending order

In [58]:
# sorted(list(enumerate(similarity[5])) , reverse = True , key = lambda x : x[1])

In [59]:
def recommend(movie):
    movie = "".join(movie.lower().split())
    title_list = new_df['title'].apply(lambda x: "".join((x.lower().split())))
    
    if movie in title_list.values:
        idx = title_list[title_list == movie].index[0]
        similar_movie = sorted(list(enumerate(similarity[idx])) , reverse = True , key = lambda x : x[1])
    
        for i in similar_movie[1:6]:
            print(new_df.iloc[i[0]].title.title())
            
    # .title() is used to print in 'Batman & Robin' this format because we change it to 'batman and robin' format
    
    else :
        print('Please enter another movie name')


**Try recommendation**

In [61]:
recommend('Titanic')

The Notebook
Under The Same Moon
Ghost Ship
The Bounty
Poseidon
